services:
  - type: web
    name: wuwawebtool
    runtime: docker
    repo: https://github.com/eventhorizonsky/WuwaWebTool
    plan: free
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /api/health
